# Generated by Django 5.2.13 on 2026-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaderboard_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='leaderboard_message_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='leaderboard_message_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='medium', max_length=10),
        ),
    ]
