# Generated by Django 5.2.13 on 2026-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_leaderboard_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
