# Generated by Django 5.2.13 on 2026-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreference_height_cm_userpreference_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='recommended_link',
            field=models.URLField(blank=True),
        ),
    ]
