# Generated by Django 5.2.13 on 2026-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpreference_recommended_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_url_pending',
            field=models.URLField(blank=True),
        ),
    ]
