# Generated by Django 5.2.13 on 2026-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_pic_url_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='daily_calories_target',
            field=models.PositiveIntegerField(default=2500),
        ),
    ]
