# Generated by Django 5.2.13 on 2026-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpreference_daily_calories_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='daily_calories_target',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url_pending',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
