# Generated by Django 5.2.13 on 2026-05-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userpreference_daily_calories_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leaderboard_message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leaderboard_message_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leaderboard_message_week',
        ),
    ]
