# Generated by Django 5.2.13 on 2026-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_set_beta_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='hide_from_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
