# Generated by Django 5.2.13 on 2026-05-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cheer_message',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
