# Generated by Django 5.2.13 on 2026-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userpreference_cheer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='cheer_message',
            field=models.CharField(blank=True, default='Believe in yourself!', max_length=240),
        ),
    ]
