# Generated by Django 5.2.13 on 2026-04-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bodymeasurement',
            new_name='fitness_bod_user_id_b2339c_idx',
            old_name='fitness_bod_user_id_32cc3f_idx',
        ),
        migrations.RenameIndex(
            model_name='exercise',
            new_name='fitness_exe_categor_94e8a9_idx',
            old_name='fitness_exe_categor_b8e5f2_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciselog',
            new_name='fitness_exe_user_id_4575ce_idx',
            old_name='fitness_exe_user_id_b31e30_idx',
        ),
        migrations.RenameIndex(
            model_name='goalplan',
            new_name='fitness_goa_user_id_008b1a_idx',
            old_name='fitness_goa_user_id_042f9c_idx',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_time_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goalexercise',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
