# Generated by Django 5.2.13 on 2026-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_csvrequest_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('message_prefix', models.CharField(default='Maintenance Duty Notice: Scheduled from', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
