# Generated by Django 5.2.13 on 2026-04-30 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_maintenancenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_part',
            field=models.CharField(choices=[('biceps', 'Biceps'), ('forearms', 'Forearms'), ('chest', 'Chest'), ('waist', 'Waist'), ('hips', 'Hips'), ('thigh', 'Thigh'), ('calf', 'Calf'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=24),
        ),
        migrations.CreateModel(
            name='ExerciseCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exercise_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
