# Generated by Django 5.2.13 on 2026-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
