# Generated by Django 5.2.13 on 2026-05-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_adminmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='EST', max_length=50)),
                ('message', models.TextField(default="MAINTENANCE WORK WILL TAKE PLACE. DON'T WORRY, THE APP IS SAFE.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
