# Generated by Django 5.2.13 on 2026-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_maintenancenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('shoulder', 'Shoulder'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('arms', 'Arms'), ('calisthenics', 'Calisthenics'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
