# Generated by Django 5.2.13 on 2026-05-07 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('machine', 'Machine'), ('calisthenics', 'Calisthenics')], default='machine', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('shoulder', 'Shoulder'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('arms', 'Arms'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalexercise',
            name='reps',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='goalexercise',
            name='sets',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
