# Generated by Django 5.2.13 on 2026-05-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_weeklyshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='is_pr_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='superset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goalexercise',
            name='is_pr_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goalexercise',
            name='superset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
