# Generated by Django 5.2.13 on 2026-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_exerciselog_is_pr_set_exerciselog_superset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('machine', 'Machine'), ('calisthenics', 'Calisthenics'), ('pr', 'PR')], default='machine', max_length=20),
        ),
    ]
